# Generated by Django 3.1.1 on 2020-10-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0003_servicedata_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedata',
            name='avgResponseTime',
        ),
        migrations.AddField(
            model_name='servicedata',
            name='qos',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
