# Generated by Django 3.1.1 on 2020-10-21 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0005_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='endpoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
