# Generated by Django 3.1.1 on 2020-10-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0006_service_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='deploymentLoss',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='failureLoss',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='loadBalancingLoss',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
