# Generated by Django 3.1.1 on 2020-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0007_auto_20201031_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedata',
            name='deploymentLoss',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicedata',
            name='failureLoss',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicedata',
            name='loadBalancingLoss',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
