# Generated by Django 3.1.1 on 2020-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0009_auto_20201031_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='violation_detected',
            field=models.BooleanField(default=False),
        ),
    ]
