# Generated by Django 3.1.1 on 2020-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0010_service_violation_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='system',
            field=models.CharField(default='accounting system', max_length=200),
            preserve_default=False,
        ),
    ]
