# Generated by Django 3.1.1 on 2020-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_webservice', '0014_service_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='scenario',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
